version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "3000:80"
    networks:
      - ugmk-network
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "3001:3001"
    networks:
      - ugmk-network

networks:
  ugmk-network:
    driver: bridge